# Generated by Django 2.1.3 on 2020-05-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0023_view_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='conversation_log',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('conversation', models.CharField(db_column='conversation', max_length=255)),
                ('start_time', models.CharField(db_column='start_time', max_length=255)),
                ('end_time', models.CharField(db_column='end_time', max_length=255)),
            ],
        ),
    ]
