# Generated by Django 2.1.3 on 2020-05-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0024_conversation_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation_log',
            name='stuname',
            field=models.CharField(db_column='stuname', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='conversation_log',
            name='stunum',
            field=models.CharField(db_column='stunum', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='conversation_log',
            name='conversation',
            field=models.CharField(db_column='conversation', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='conversation_log',
            name='end_time',
            field=models.CharField(db_column='end_time', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='conversation_log',
            name='start_time',
            field=models.CharField(db_column='start_time', default='', max_length=255),
        ),
    ]
