# Generated by Django 2.1.3 on 2020-05-05 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0025_auto_20200505_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation_log',
            name='createtime',
            field=models.DateTimeField(db_column='createtime', default=django.utils.timezone.now),
        ),
    ]
